[project]
name = "bdl"
description = """
Python library for interacting with Bank Danych Lokalnych API.
"""

dependencies = [
    "httpx == 0.27.0",
]

requires-python = '>=3.9'

[project.optional-dependencies]
pandas = [
    "pandas == 2.2.1"
]
